/**
 * Ajax Alexa Thumbnails - 0.3
 * 
 * @author		Eric Ferraiuolo <eferraiuolo@gmail.com>
 * @copyright	2008 Eric Ferraiuolo
 * @license		GNU LGPL <http://www.gnu.org/licenses/lgpl.html>
 */


(function(){if(typeof YAHOO=="undefined"){throw"YAHOO Golbal Object is required.";}if(typeof EDF=="undefined"){EDF={};}EDF.Thumbnail={};EDF.Thumbnail.Dependencies=function(){var A={};var B=null;var C={addModule:function(D,E){if(!YAHOO.lang.isString(D)){throw new TypeError("module must be a String.");}if(!YAHOO.lang.isUndefined(A[D])){throw new TypeError("Module: "+D+" is already defined.");}if(!YAHOO.lang.isString(E.requires)&&!YAHOO.lang.isArray(E.requires)){throw new TypeError("dependencies.requires must be a String or an Array.");}if(!YAHOO.lang.isFunction(E.check)){throw new TypeError("dependencies.check must be a Function.");}A[D]=E;},load:function(D,E){if(!YAHOO.lang.isString(D)){throw new TypeError("module must be a String.");}if(YAHOO.lang.isUndefined(A[D])){throw D+" isn't a valid Thumbnail module";}if(!YAHOO.lang.isFunction(E)){throw new TypeError("callback must be a function.");}if(A[D].check()){return E();}else{if(!YAHOO.util.YUILoader){throw"YUI dependencies: "+A[D].requires+" are required unless YAHOO.util.YUILoader is provided.";}else{B=new YAHOO.util.YUILoader({require:A[D].requires,onSuccess:E});B.insert();}}}};return C;}();EDF.Thumbnail.Service=function(){var H={requires:["dom","event","connection"],check:function(){return(YAHOO.util.Dom&&YAHOO.util.Event&&YAHOO.util.Connect)?true:false;}};var D=false;var C=null;var G=[];var B=function(I){var J=function(K){if(K.indexOf("http://")===0){return true;}else{return false;}};if(J(I)){return I.substring(7,I.indexOf("/",7)>=0?I.indexOf("/",7):I.length);}else{return I;}};var A=function(I){I=B(I);for(var J in G){if(I==G[J].request){return G[J].response;}}return null;};var E=function(J,I){J=B(J);for(var K in G){if(J==G[K].request){G[K].response=I;return I;}}G.push({request:J,response:I});return I;};var F={init:function(I,J){if(D){return J();}if(!YAHOO.lang.isString(I)){throw new TypeError("sourceURL must be a string.");}if(!YAHOO.lang.isFunction){throw new TypeError("callback must be a function.");}EDF.Thumbnail.Dependencies.load("Service",function(){C=I;D=true;J();});},getThumbnail:function(J,O,I){if(!D){throw"Thumbnail Service hasn't been initialized.";}if(!YAHOO.lang.isString(J)){throw new TypeError("url must be a string.");}if(!YAHOO.lang.isFunction(O)){throw new TypeError("callback must be a function.");}var N=A(J);if(YAHOO.lang.isValue(N)){return O(N);}else{var M={size:"Small"};I=YAHOO.lang.merge(M,(I||{}));var L=C+"?url="+J+"&size="+I.size.substr(0,1).toUpperCase()+I.size.substr(1);var K=YAHOO.util.Connect.asyncRequest("GET",L,{success:function(P){N=E(J,P.responseText);return O(N);},failure:function(P){return O(null);}});}}};EDF.Thumbnail.Dependencies.addModule("Service",H);return F;}();})();
